Add php-8.0 support
totara/totara-docker-dev pull request #106
Opened 2020-09-06 09:53 UTC by samanthajayasinghe

2020-09-17 11:05 UTC, derschatta requested changes

2020-09-17 11:05 UTC, derschatta commented on compose/php.yml
> +  php-8.0-debug:
if xdebug is not supported yet maybe we should just leave out the container completely

2020-09-17 11:05 UTC, derschatta commented on php/php80/Dockerfile
> +FROM php:8.0-rc-fpm
shall we pin this to  `8.0.0beta3-fpm` for now and raise it manually once a new version comes out?

2020-09-17 11:05 UTC, derschatta commented on php/php80/Dockerfile
> +        mysqli \
add `exif` here too (patch for the other versions adding this just got merged)

2020-09-18 00:05 UTC, samanthajayasinghe commented on README.md
> +php74 | 8.0 |  [Dockerfile](https://github.com/totara/totara-docker-dev/blob/master/php/php80/Dockerfile) | [![Build status PHP 8.0](https://img.shields.io/docker/build/totara/docker-dev-php80.svg)](
Done

2020-09-18 00:05 UTC, samanthajayasinghe commented on README.md
> +php74-debug | 8.0 + xdebug 2.9.6 |  [Dockerfile](https://github.com/totara/totara-docker-dev/blob/master/php/php80-debug/Dockerfile) | [![Build status PHP 8.0 Debug](https://img.shields.io/docker/bui
xdebug is not working and removed the container

2020-09-18 00:06 UTC, samanthajayasinghe commented on compose/php.yml
> +  php-8.0-debug:
done

2020-09-18 00:06 UTC, samanthajayasinghe commented on php/php80/Dockerfile
> +        mysqli \
done

2020-09-18 00:11 UTC, derschatta requested changes

2020-09-18 00:11 UTC, derschatta commented on README.md
> +127.0.0.1   localhost totara54 totara54.debug totara54.behat totara55 totara55.debug totara55.behat totara55 totara55.debug totara56.behat totara70 totara70.debug totara70.behat totara71 totara71.deb
debug is still present here

2020-09-18 00:11 UTC, derschatta commented on compose/nginx.yml
> +          - totara80.debug
remove debug

2020-09-18 00:11 UTC, derschatta commented on nginx/config/totara.conf
> +    server_name totara80.debug;
remove debug

2020-09-29 23:05 UTC, markmetcalfe commented
The directory ```php/php-8.0-cron``` doesn't exist, but yet in ```compose/build.yml```, ```php-8.0-cron``` is defined. This results in not being able to build any containers locally (which is probably what caused the travis build to fail too)

2020-09-30 01:15 UTC, samanthajayasinghe commented on php/php80/Dockerfile
> +FROM php:8.0-rc-fpm
done

2020-10-09 01:40 UTC, samanthajayasinghe commented
> The directory `php/php-8.0-cron` doesn't exist, but yet in `compose/build.yml`, `php-8.0-cron` is defined. This results in not being able to build any containers locally (which is probably what caused the travis build to fail too)

@markmetcalfe php-8.0-cron dir and DockerFile is in this  PR. just rebase the PR

2020-10-27 19:20 UTC, derschatta requested changes

2020-10-27 19:20 UTC, derschatta commented on php/php80/Dockerfile
> +FROM php:8.0.0beta3-fpm
@samanthajayasinghe can you update this to `php:8.0.0rc-fpm`?

2020-10-27 19:20 UTC, derschatta commented on README.md
> +php80 | 8.0-beta3 |  [Dockerfile](https://github.com/totara/totara-docker-dev/blob/master/php/php80/Dockerfile) | [![Build status PHP 8.0](https://img.shields.io/docker/build/totara/docker-dev-php80.
8.0-rc

2020-10-27 19:47 UTC, derschatta commented on php/php80/Dockerfile
> +FROM php:8.0.0beta3-fpm
hm that did not seem to work for me, still got beta3 after building, maybe try `php:8.0.0RC2-fpm-buster`

2020-10-27 20:06 UTC, derschatta commented
@samanthajayasinghe could you also reword the PR and the commit messages to include "experimental support" for PHP 8? That would make it clear that this is not final / stable

2021-04-16 01:41 UTC, derschatta commented on README.md
> +php80 | 8.0-beta3 |  [Dockerfile](https://github.com/totara/totara-docker-dev/blob/master/php/php80/Dockerfile) | [![Build status PHP 8.0](https://img.shields.io/docker/build/totara/docker-dev-php80.
we should update this as it's the final version now

2021-04-16 01:42 UTC, derschatta commented on compose/nginx.yml
> +          - totara80
I think xdebug 3.0.0 add PHP support so we can add `totara80.debug`

2021-04-16 01:43 UTC, derschatta commented on compose/php.yml
> +  php-8.0:
add a section for php-8.0-debug

2021-04-16 01:43 UTC, derschatta commented on nginx/config/totara.conf
> +server {
add a section for totara80.debug

2021-04-16 01:45 UTC, derschatta requested changes
only changing the version in the readme.

let's add xdebug suppport using Xdebug 3.0.4 in a separate patch

2021-04-16 01:57 UTC, samanthajayasinghe commented on nginx/config/totara.conf
> +server {
will create separate PR to fix php80 xdbug

2021-04-16 01:57 UTC, samanthajayasinghe commented on compose/nginx.yml
> +          - totara80
will create separate PR to fix php80 xdbug

2021-04-16 01:57 UTC, samanthajayasinghe commented on README.md
> +php80 | 8.0-beta3 |  [Dockerfile](https://github.com/totara/totara-docker-dev/blob/master/php/php80/Dockerfile) | [![Build status PHP 8.0](https://img.shields.io/docker/build/totara/docker-dev-php80.
done

2021-04-16 02:04 UTC, derschatta approved these changes

2021-04-16 02:05 UTC, merged