Small improvements to t commands
totara/totara-docker-dev pull request #119
Opened 2020-09-16 20:30 UTC by derschatta

fixes #118

2020-09-17 01:04 UTC, markmetcalfe requested changes

2020-09-17 10:42 UTC, derschatta commented on bin/tnpm
> +$SCRIPTPATH/tdocker run --rm -w "$TOTARASITEDIR" nodejs npm "$@"
Without the --rm the command will leave a volume behind for each tui command you trigger. With the command it just cleans up the volume used for the one run.

2020-09-17 10:43 UTC, derschatta commented on bin/tdb
> +elif [ "$db_type" == 'sqlsrv' -o  "$db_type" == 'mssql' ]; then
Just wanted to be consistent to the other conditions here and keep using single brackets, but happy to change it nevertheless

2020-09-17 10:51 UTC, derschatta commented on bin/tbash
> +# If tnpm is called from a subdirectory, then we run npm in that subdirectory too
changed

2020-09-17 10:51 UTC, derschatta commented on bin/tdb
> +elif [ "$db_type" == 'sqlsrv' -o  "$db_type" == 'mssql' ]; then
changed

2020-09-17 12:24 UTC, derschatta commented
this also tackles #110 now adding support for changing the backup path via the .env file and also removing the need of specifing full file paths/names. Now you just choose a name for the backup and tdb will take care of putting it into the right place and it will also attach the dbhost.

so `tdb backup totara_13 mybackup` will result in `~/tdb_backup/mybackup.pgsql11` for example.

2020-09-18 00:06 UTC, markmetcalfe commented on bin/tnpm
> +$SCRIPTPATH/tdocker run --rm -w "$TOTARASITEDIR" nodejs npm "$@"
Ah cool yeah its annoying how it did that

2020-09-18 00:10 UTC, derschatta commented
@markmetcalfe if you are fine with the changes please approve the review

2020-09-18 00:28 UTC, markmetcalfe reviewed
> this also tackles #110 now, adding support for changing the backup path via the .env file and also removing the need of specifying full file paths/names. Now you just choose a name for the backup and tdb will take care of putting it into the right place and it will also attach the dbhost.
> 
> so `tdb backup totara_13 mybackup` will result in `~/tdb_backup/mybackup.pgsql11` for example.

I'm not a fan of restricting backups to only be able to be used in the same version. If its done like this, then you can't backup a postgres 11 database and then restore it into postgres 12 for instance. Instead I think it should be that you also specify the host when backing up restoring like
tdb backup totara13 bigdata.pgsql11
tdb restore totara13 bigdata.pgsql11

2020-09-18 00:34 UTC, derschatta commented
> > this also tackles #110 now, adding support for changing the backup path via the .env file and also removing the need of specifying full file paths/names. Now you just choose a name for the backup and tdb will take care of putting it into the right place and it will also attach the dbhost.
> > so `tdb backup totara_13 mybackup` will result in `~/tdb_backup/mybackup.pgsql11` for example.
> 
> I'm not a fan of restricting backups to only be able to be used in the same version. If its done like this, then you can't backup a postgres 11 database and then restore it into postgres 12 for instance. Instead I think it should be that you also specify the host when backing up restoring like
> `tdb backup totara13 bigdata.pgsql11`
> `tdb restore totara13 bigdata.pgsql11`

what about a compromise and we use the database type instead, so it would become `totara13 bigdata.pgsql` and you could restore it into any db. The reason I did this automatic suffixing is to make it easier for the user and if he wants to use the same name for different databases he could do so without explicitely specifying them. Also having the database type in the name is really helpful if you have a lot of dumps.

2020-09-18 00:41 UTC, markmetcalfe commented
> what about a compromise and we use the database type instead, so it would become `totara13 bigdata.pgsql` and you could restore it into any db of the same type? The reason I did this automatic suffixing is to make it easier for the user and if he wants to use the same name for different databases he could do so without explicitely specifying them. Also having the database type in the name is really helpful if you have a lot of dumps.
OK sure.

2020-09-20 21:28 UTC, derschatta commented
@derschatta changed the backup file names to include the db type instead of host.

I also changed the default collation for mariadb/mysql as utf8_unicode_ci is not the right one.

2020-09-20 22:12 UTC, markmetcalfe requested changes
@derschatta Can you also change the char set and collation for mariadb too? Then we can close off #107

2020-09-20 22:25 UTC, derschatta commented
> @derschatta Can you also change the char set and collation for mariadb too? Then we can close off #107

done

2020-09-21 00:08 UTC, markmetcalfe requested changes
Found issues while testing, can merge https://github.com/derschatta/totara-docker-dev/pull/2/files into this to fix them

2020-09-21 00:20 UTC, markmetcalfe approved these changes

2020-09-21 00:32 UTC, merged