Improve ngrok support
totara/totara-docker-dev pull request #142
Opened 2021-04-20 03:40 UTC by markmetcalfe

Currently there is no guide on how to get docker-dev working with ngrok. This patch adds documentation, along with a new 'tngrok' command which simplifies the command required to get ngrok up and running with docker-dev. This patch also includes a config.php snippet for automatically setting the correct wwwroot.

2021-04-20 21:55 UTC, simoncoggins approved these changes
I haven't tested but from reading the code this looks good to me.

2021-04-20 22:55 UTC, markmetcalfe commented
I'll give this a test quickly with the old setup. Also might be worth seeing if we can get the paid version of ngrok available for us, then it might be worth adding another tngrok argument for specifying the static URL

2021-06-28 02:27 UTC, derschatta requested changes
tested it successfully with some modifications, see comments

2021-06-28 02:27 UTC, derschatta commented on nginx/entrypoint.sh
> +versions=("22" "24" "25" "26" "27" "29" "9" "10" "11" "12" "13" "14")
we need 15 now too

2021-07-06 10:13 UTC, markmetcalfe commented on nginx/entrypoint.sh
> +versions=("22" "24" "25" "26" "27" "29" "9" "10" "11" "12" "13" "14")
fixed

2021-07-06 10:16 UTC, markmetcalfe commented on README.md
> +__[Ngrok](https://ngrok.com/)__ is a useful tool for making your local totara site accessible publicly on the web.
done

2021-07-06 10:16 UTC, markmetcalfe commented on README.md
> +if (!empty($_SERVER['HTTP_X_ORIGINAL_HOST'])) {
fixed

2021-07-06 10:16 UTC, markmetcalfe commented
@derschatta Fixed your comments. Could you approve this?

2021-07-21 21:05 UTC, derschatta requested changes
just the one comment. rest looks good and works well

2021-07-21 23:10 UTC, markmetcalfe commented on bin/tngrok
> +#!/bin/bash
@derschatta Fixed

2021-07-22 02:39 UTC, derschatta approved these changes

2021-07-22 02:40 UTC, merged