Add better compatibility between tdb database backups and totara box databases
totara/totara-docker-dev pull request #149
Opened 2021-07-22 08:42 UTC by markmetcalfe

This adds a new argument for the `tdb` command: `--totara-box`, which when specified, means that `tdb` will attempt to backup/restore in the same format as totara box does. This means that you can easily backup to and restore from a totara box site.

2021-08-03 00:24 UTC, derschatta requested changes
while testing this (the restore of a box dump worked as expected) I noticed that you can only do `tdb -i -b restore` but not `tdb -b -i restore` so the order of the parameters matters but that might not be obvious to a user. Potentially worth fixing

2021-08-03 03:58 UTC, markmetcalfe commented on bin/tdb
> +        if [ "$for_totara_box" == "0" ]; then
done

2021-08-03 03:58 UTC, markmetcalfe commented
> while testing this (the restore of a box dump worked as expected) I noticed that you can only do `tdb -i -b restore` but not `tdb -b -i restore` so the order of the parameters matters but that might not be obvious to a user. Potentially worth fixing

Have fixed this, could you take a look again?

2021-08-03 04:13 UTC, markmetcalfe commented
@derschatta I've also just added a commit that adds a `-f`/`--force-backup` flag which allows force overwriting an existing backup. This will resolve #109

2021-08-13 04:03 UTC, derschatta approved these changes
the --force flag is awesome, thanks! :)

2021-08-13 04:03 UTC, derschatta commented on bin/tdb
> +  -b, --totara-box         Backup and restore the database in a format compatible with Totara box (Postgres only)
it works but it could have more instructions. You have to know that you gotta rename the box file to something tdb can work with...but for now I would say it's good enough

2021-08-13 04:03 UTC, derschatta commented on bin/tdb
> +  -b, --totara-box         Backup and restore the database in a format compatible with Totara box (Postgres only)
also it might be worth to improve it in the future so that you can just download both files, the .dump and the .tar.gz for the dataroot and be able to import them without renaming anything.

2021-08-13 04:03 UTC, merged