Add mariadb 10.6 support
totara/totara-docker-dev pull request #151
Opened 2021-07-26 21:43 UTC by samanthajayasinghe

2021-08-02 23:52 UTC, derschatta requested changes

2021-08-02 23:52 UTC, derschatta commented on compose/mariadb.yml
>    mariadb:
changing the default here does create a few issues if you are already using this container, people would have to delete the old container and volumes before being able to use it.

I wonder if it's better to leave that one for now or just don't have a generic mariadb container but name all db containers with their specific version

2021-08-02 23:52 UTC, derschatta commented on compose/mariadb.yml
> +      - "3310:3306"
we should not change the port as developers have set it up already

2021-08-02 23:52 UTC, derschatta commented on compose/mariadb.yml
>    mariadb:
when we release this we have to put some notes in the release notes

2021-10-01 03:58 UTC, markmetcalfe commented
Comments resolved in #163

2021-10-01 03:58 UTC, closed without merging