Add tphp command
totara/totara-docker-dev pull request #233
Opened 2022-12-21 22:44 UTC by scq

This PR adds a tphp command for executing commands inside the php container.

Example:

```
sc ~/c/t/learn> tdb drop
Successfully dropped pgsql14 database learn_17
sc ~/c/t/learn> tdb create
Successfully created pgsql14 database learn_17
sc ~/c/t/learn> tphp install
Using PHP Container: php-8.1
Running Command: php server/admin/cli/install_database.php --adminpass=admin --adminemail=admin@example.com --agree-license --shortname=Totara 17 development site --fullname=Totara 17 development site
Totara 17.0+ (Build: 20221108.00) command line installation program
-------------------------------------------------------------------------------
== Setting up database ==
-->System
++ Success ++
-->totara_core
++ Success ++
```

This makes it a bit more convenient to use the install/cron/purge/etc aliases without needing to tbash in to the container.

2023-03-08 04:04 UTC, scq commented on bin/tphp
> +    $script_path/tbash php
That's a good point! How about a variable in .env?

I've called it `INTERACTIVE_SHELL` since SHELL is an existing standard environment variable (and we only use the variable where we want an interactive shell, otherwise we use bash), but open to better naming suggestions. It defaults to bash.

We could potentially also add a `tshell` command that runs either bash or zsh depending on your configuration, but I haven't done it here. Might be useful to use in the docs.

2023-03-08 04:04 UTC, scq commented on bin/tbash
>  #!/bin/bash
Oh, true -- updated.

2023-08-29 00:16 UTC, derschatta approved these changes
looks good :)

2023-08-29 01:32 UTC, scq commented
I've been using it locally for a while and discovered some issues with handling of args recently, will just convert it to a draft until I fix those

2024-08-19 05:02 UTC, derschatta commented on bin/tphp
> +    $script_path/tbash php
sorry for the late reply @scq but I like the .env idea.

2024-08-19 05:04 UTC, derschatta commented
> I've been using it locally for a while and discovered some issues with handling of args recently, will just convert it to a draft until I fix those

Hey @scq how far are you away from converting this back to a regular merge request and get it in? Would be a great addition.

2024-08-19 05:14 UTC, scq commented
@derschatta I still need to solve the issue with passing arguments -- it will fail if it gets passed arguments that are too complex. I'll try and take a look at this again to get that working :D

2024-08-19 06:32 UTC, scq commented
Fixed the issues. Bash is currently broken though, so it needs #282 first.

Things you can do:

* `tphp` -- start your preferred shell in the php container (make sure to set INTERACTIVE_SHELL in .env)
* `tphp ls` -- run arbitrary commands in the php container
* `tphp install` -- run sh aliases
* `tphp dev/approval/simple/create_demo.php` -- run php scripts
* `tphp server/admin/tool/task/cli/schedule_task.php --execute='\tool_diagnostic\task\delete_diagnostic_files_task'` -- run complex commands

It autodetects if the first argument ends in .php and adds `php ` on to the beginning, because I found that I kept leaving it off (and `tphp php ...` looks a little weird)

2024-08-19 22:03 UTC, scq commented
Changed `INTERACTIVE_SHELL` default to `zsh`, seems like hardly anybody is using `bash` given #282

2024-08-20 01:47 UTC, derschatta commented
There must be something specific needed for MacOS as I get:

`/Users/username/folder/totara/docker/bin/tphp: line 13:  ${i@Q}: bad substitution`

2024-08-20 01:52 UTC, derschatta requested changes
there's a bug on MacOS, see previous comment

2024-08-20 04:04 UTC, scq commented
Oh weird. I think Apple ships an ancient bash version that doesn't seem to support that parameter expansion syntax, will see if I can find another way to do it (the @Q is needed to quote the parameter).

2024-08-22 23:29 UTC, scq commented
@derschatta okay, that should be fixed now

2024-09-09 22:15 UTC, derschatta approved these changes
works like a charme now

2024-09-09 22:15 UTC, merged