replace base image to alpine
totara/totara-docker-dev pull request #240
Opened 2023-05-21 23:26 UTC by NingZhou-NZ

I replced the base image of apache, nginx, postgresql, nodejs, redis and memcache to alpine linux. I also add mariadb10.9 and postgresql 15 to the list.
The reason for replacement were that alpine linux is smaller and consume less resource and less vulnerability.
I will replace those php image in next commit.

2023-05-22 00:35 UTC, derschatta commented
Haven't had a chance to look at the full amount of changes but there's definitely too many different things put into one PR/commit. Can the changes to alpine be separated from the introduction of new containers? Any change not related should be in it's own PR.

2023-06-13 07:18 UTC, NingZhou-NZ commented
@codyfinegan @derschatta I seperated my original commit to four different commits

2023-06-13 09:22 UTC, NingZhou-NZ commented
I also added method for creating image according to the cpu architecture

2023-09-04 00:24 UTC, derschatta requested changes
@NingZhou-NZ I think we should get some of the changes in here in. Although this now requires a rebase and some changes (see my comments).

2023-09-04 00:24 UTC, derschatta commented on php/php81/config/php.ini
> -max_input_vars = 2000
why was this change necessary?

2023-09-04 00:24 UTC, derschatta commented on php/php81/Dockerfile
Changes in the PHP Dockerfiles are obsolete, they have been updated to bullseye in #248.

Moving the PHP containers to alpine is possible I think but requires a bit more work. I have experimented with it locally and can add a followup patch at a later stage.

2023-09-04 00:24 UTC, derschatta commented on nginx/Dockerfile
> +FROM $ARCH/nginx:alpine
remove ARCH (we don't want to optimise for only one architecture, rather build an image which supports both, arm and amd).

And change image to `nginx:1.25-alpine`

2023-09-04 00:24 UTC, derschatta commented on compose/pgsql.yml
> +    image: postgres:9.3-alpine
all the pgsql images have been changed to alpine in #250

2023-09-04 00:24 UTC, derschatta commented on compose/pgsql.yml
> +      POSTGRES_HOST_AUTH_METHOD: trust
what happens without this environment variable?

2023-09-04 00:24 UTC, derschatta commented on bin/tbuild
> +if [ $(uname -m) == "arm64" ]; then
doesn't it automatically use the one you are currently running?

2023-09-04 00:24 UTC, derschatta commented on apache/Dockerfile
> +FROM $ARCH/httpd:2.4-alpine
remove the ARCH, we don't want to build only for one architecture.

2023-09-04 00:27 UTC, derschatta commented on docker-compose.yml
> +    image: node:16-alpine3.16
maybe should be `node:16-alpine`?

2023-09-04 00:29 UTC, derschatta commented on docker-compose.yml
> +    container_name: totara_redis
this could create problems if someone has been running it before, conflicts with existing containers. Not strictly necessay anyway, so maybe it's safer to not add container names in this patch.

2023-09-04 02:07 UTC, NingZhou-NZ commented on compose/pgsql.yml
> +      POSTGRES_HOST_AUTH_METHOD: trust
I think I try to remove the db password from local image.

2023-09-04 03:14 UTC, derschatta commented on apache/Dockerfile
> +FROM $ARCH/httpd:2.4-alpine
also docker will automatically pick the right arch depending on the host I believe.

2023-09-05 03:16 UTC, derschatta commented
actually I just found out that alpine has difference uid/guid for www-data. In the entrypoint.sh for nginx we are setting the ownership of the data root folder to www-data. This is problematic if not all images accessing it use alpine. I think we should hold off mixing alpine and non-alpine for now. It only works if all images are based on alpine I think. Maybe except the database containers as they are pretty self-contained.

2023-09-05 03:21 UTC, derschatta commented
was able to convert two of the PHP images to use the alpine base images, see #252 as a draft

2025-06-30 23:53 UTC, markmetcalfe commented
Closing this PR as it's been inactive for 2+ years

2025-06-30 23:53 UTC, closed without merging