Fix ssl package dependency
totara/totara-docker-dev pull request #244
Opened 2023-07-04 02:34 UTC by derschatta

Builds are failing due to a missing dependency.

```
 > [php-8.0 10/29] RUN wget "http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u12_amd64.deb"     && DEBIAN_FRONTEND=noninteractive dpkg -i ./libssl1.0.0_1.0.1t-1+deb8u12_amd64.deb:
#0 0.302 --2023-07-04 01:31:15--  http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u12_amd64.deb
#0 0.302 Resolving security.debian.org (security.debian.org)... 151.101.130.132, 151.101.66.132, 151.101.2.132, ...
#0 0.425 Connecting to security.debian.org (security.debian.org)|151.101.130.132|:80... connected.
#0 0.443 HTTP request sent, awaiting response... 404 Not Found
#0 0.747 2023-07-04 01:31:16 ERROR 404: Not Found.
```

I've update the dependency to the latest one.

2023-08-28 23:52 UTC, scq commented on php/php74/Dockerfile
> +Dockerfile
typo?

2023-08-29 00:56 UTC, derschatta commented on php/php74/Dockerfile
> +Dockerfile
Good catch, will fix it

2023-08-29 01:11 UTC, scq requested changes
This is a pretty interesting one.

All of the containers older than PHP 7.2 no longer build, as Debian 9 (stretch) ended support and the packages were moved to the archive. It should be possible to make them build again by updating sources.list to point to the archive, but at the moment, they are not building. Not sure if we want to address this in this ticket or elsewhere.

The revised URL for the libssl .deb is now also 404ing.

It looks like Microsoft actually fixed the issue with the MSSQL driver though, and manually adding that specific version (1.0.0) of libssl is no longer necessary, at least in Debian 10 (can't test with 9 as the containers won't build).

2023-08-29 01:45 UTC, derschatta commented
> 

Thanks @scq  I'll have another look

2023-08-29 04:46 UTC, derschatta commented
@scq  ok took me a while to get all the builds running again (at least back to 5.6). It's awesome to be able to get rid of that annoying ssl dependency.

Please have another look

2023-08-29 06:13 UTC, scq approved these changes
Woo, nice one! Looks good :D

2023-08-29 08:02 UTC, merged

2023-08-29 20:53 UTC, derschatta commented
fixes #237