Fix checknet.txt for SCORM not being able to called
totara/totara-docker-dev pull request #247
Opened 2023-08-30 21:54 UTC by derschatta

Fixes #232

2023-09-05 03:25 UTC, derschatta commented
please ignore the build failures, not sure what happened there.

2023-09-05 22:05 UTC, NathanielWalmsley requested changes
I tried this using `ngrok` on a T18 site. I still persistently received the reported error at frequent intervals. I followed the instructions on Issue 232, and was able to reproduce the issue, but these changes did not resolve it.

2023-09-06 21:58 UTC, NathanielWalmsley approved these changes

2023-09-06 21:58 UTC, derschatta commented
Found another issue where one of the regex blocked valid requests, e.g. `/lib/yuilib/3.17.2/datatype-date-format/lang/datatype-date-format_en-US.js` and fixed it

2023-09-06 21:59 UTC, merged