Adding PHP 8.2 images
totara/totara-docker-dev pull request #257
Opened 2023-10-31 22:49 UTC by codyfinegan

I've based them off the existing setup for now, not the WIP alpine image.

Dropped the python for recommenders inside the php image as it's not needed.

2023-11-01 04:56 UTC, derschatta requested changes
a few things to look at

2023-11-01 04:56 UTC, derschatta commented on compose/php.yml
> +    container_name: totara_php82_cron
php83

2023-11-01 04:56 UTC, derschatta commented on php/php83-debug/Dockerfile
> +RUN pecl install -f xdebug-3.3.0 && docker-php-ext-enable xdebug.so
I think 3.3.0 is not out fully, only `3.3.0alpha3`

2023-11-01 04:56 UTC, derschatta commented on README.md
> + * [PHP](http://php.net/) 5.3, 5.4, 5.5, 5.6, 7.0, 7.1, 7.2, 7.3, 7.4, 8.0, 8.1, 8.2, 8.3 to test for different versions
8.3RC

2023-11-01 04:57 UTC, derschatta commented
@codyfinegan  I've also created the repositories required on Docker Hub so theoretically they should build the images automatically once this gets merged

2023-11-01 21:32 UTC, codyfinegan commented on php/php83-debug/Dockerfile
> +RUN pecl install -f xdebug-3.3.0 && docker-php-ext-enable xdebug.so
Yep, 3.3.0 installs the alpha version currently
> .789 WARNING: failed to download pecl.php.net/xdebug, version "3.3.0", will instead download version 3.3.0alpha3, stability "beta"

But it's better to lock into the alpha version & we update it after 8.3 goes live so I've changed to the alpha tag specifically

2023-11-01 21:32 UTC, codyfinegan commented
> a few things to look at

Cheers, those are all updated.

2023-11-01 22:48 UTC, derschatta approved these changes

2023-11-01 22:49 UTC, derschatta commented
looks good. Have not tested it yet. Want me to also build and test them?

2023-11-01 23:18 UTC, codyfinegan commented
> looks good. Have not tested it yet. Want me to also build and test them?

Yes please. I've tested building locally (so all the images should build) but haven't had a chance to actually run them yet.

2023-11-14 00:28 UTC, scq approved these changes

2023-11-14 03:35 UTC, derschatta commented
sorry couldn't get to testing this yet. @scq have you been able to?

2023-11-14 03:54 UTC, scq commented
@derschatta Yup, I can confirm all 4 containers work

2023-11-14 03:54 UTC, merged