OPS-1838: Set default collation for MySQL & Mariadb images to utf8mb4_unicode_ci
totara/totara-docker-dev pull request #265
Opened 2024-04-12 03:30 UTC by Kunleodusan

2024-04-14 20:58 UTC, jakub-krauz-totara approved these changes

2024-04-28 22:22 UTC, derschatta requested changes
@Kunleodusan patches need to go to the develop branch, not master

2024-06-18 22:05 UTC, codyfinegan approved these changes

2024-06-18 22:42 UTC, navjeet-totara commented
I have given a test on integration branch with php-8.1 with mariadb 10.11 and mysql8.
I was able to install site via CLI and Web

2024-06-18 22:45 UTC, merged